apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather-backend
  template:
    metadata:
      labels:
        app: weather-backend
    spec:
      containers:
        - name: weather-backend
          image: rleonard02/weather-backend:latest
          ports:
            - containerPort: 8000
          env:
            - name: WEATHER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: weather-api-key
                  key: WEATHER_API_KEY
