apiVersion: v1
kind: Service
metadata:
  name: weather-backend-service
spec:
  selector:
    app: weather-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
