apiVersion: v1
kind: Service
metadata:
  name: weather-frontend-service
spec:
  type: NodePort
  selector:
    app: weather-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001 # This is the port on your host machine
