apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-frontend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather-frontend
  template:
    metadata:
      labels:
        app: weather-frontend
    spec:
      containers:
        - name: weather-frontend
          image: rleonard02/weather-frontend:latest
          ports:
            - containerPort: 80
